name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Read version from package.json
      id: get-version
      run: |
        VERSION=$(jq -r .version package.json)
        IMAGE_NAME=$(jq -r .name package.json | tr '[:upper:]' '[:lower:]' | tr -d '@' | tr '/' '-')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }/${{ env.IMAGE_NAME }}:latest -t ghcr.io/${{ github.repository_owner }/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
        docker push ghcr.io/${{ github.repository_owner }/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/${{ github.repository_owner }/${{ env.IMAGE_NAME }}t:${{ env.VERSION }}
